### ISSUE TITLE
Activating seedfilemonitor

### ISSUE THREAD

**Issue by cjhopp** [barsch/seishub.core#11]
Hi all,

I've recently installed seishub.core as well as seishub.plugins.seismology (via 'setup.py install' as the PyPI method no longer functions) and started a test instance locally (using a postgre back-end).

I have a small directory of day-long miniseed files which I would like to index but I cannot seem to activate the seedfilemonitor service. I've added the following to my seishub.ini file:
```
[seedfilemonitor]
autostart = True
paths = /home/chet/data/test_mseed
```
But Seedfilemonitor doesn't appear in the 'Services' tab of the web interface as shown in @barsch 's dissertation (p. 25)

I'm obviously missing something. Any insight would be much appreciated.

Chet

**Comment by barsch** [comment]
Hi Chet,

SEEDFileMonitor is started externally as extra process - it was desinged to run without an extra SeisHub instance - therefore it was outsourced into obspy.db (https://github.com/obspy/obspy/tree/master/obspy/db) so other could use it too in there product.

use ```obspy-indexer``` to start such indexing process (https://github.com/obspy/obspy/blob/master/obspy/db/scripts/indexer.py), e.g.

(1) Run indexer as daemon continuously crawling the given paths but index only
    the last 24 hours (-r24) of a waveform archive:
```
       #!/bin/bash
       DB=postgresql://username:password@localhost:5432/database
       DATA=/path/to/archive/2010,/path/to/archive/2011,/path/to/arclink
       LOG=/path/to/indexer.log
       ./obspy-indexer -v -i0.0 -n1 -u$DB -d$DATA -r24 -l$LOG &
```
(2) Run only once and remove duplicates:
```
       ./obspy-indexer -v -i0.0 --run-once --check-duplicates -n1 -u$DB -d$DATA
```

As far I remember the SEEDFileMonitor tab has been removed from the SeisHub interface - instead you could always check if the files are in the database via the waveform tab.

There is successor for SeisHub in the development - I'm not usre what its current state - but it would be smart to contact @krischer about it. Its using pretty much the same idea - but more up to date technologies.

Hope it helps,
Robert

**Comment by cjhopp** [comment]
Hi Robert, 

This helps immensely. Thanks for the quick reply!
