### ISSUE TITLE
Quick Start or Tutorial for learning basic usage?

### ISSUE THREAD

**Issue by d-chambers** [barsch/seishub.core#12]
Is there any documentation for using seishub once it has been set up? It seems http://seishub.org/ is no longer there. Is seishub still supported?

**Comment by barsch** [comment]
The main documentations are linked on the first page - there is now how to tutorial. Support for SeisHub is unfortunatly very limited. seishub.org was only a redirect to th GitHub page - I'll remove the link from the start page.

There is successor for SeisHub in the development - I'm not sure what its current state - it would be best to contact @krischer about it. Its using pretty much the same ideas but more up to date technologies.

Cheers,
Robert
